### ISSUE TITLE
Can't post embed in announcement channel

### ISSUE THREAD

**Issue by LPRG-Devs** [PranoyMajumdar/dispie#1]
Hey i use Dispie since yesterday in my Bot for my Community Server and i have a announcement channel where i send every news for the server but when i klick on send i can't see my announcement channels

**Comment by LPRG-Devs** [comment]
nope no error, i can only see the rules channel and the normal text channels

**Comment by LPRG-Devs** [comment]
so do you know how to fix it?

**Comment by PranoyMajumdar** [comment]
I have fixed the issue, please update dispie using `pip install -upgrade dispie`.
